spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://ec2-44-214-98-128.compute-1.amazonaws.com:5432/d2jqbff0j4qag1
        username: gfaxyctdxizimw
        password: f45dfaf7dbc005fa80e97071228e28637cd1727cabae0f4d5b58e41adf279485

    # JPA settings
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        database: postgresql

    flyway:
        baseline-on-migrate: true