spring:
    datasource:
        driver-class-name: org.postgresql.Driver
#        url: jdbc:postgresql://ec2-44-214-98-128.compute-1.amazonaws.com:5432/d2jqbff0j4qag1
#        username: wjetyfkceunluc
#        password: b86cd274f36a3863434df11393e229d7d0fc1fc6857a565342ac3d9bd593f853
        url: jdbc:postgresql://localhost:5432/db_shelfie
        username: postgres
        password: password

    # JPA settings
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        database: postgresql

    flyway:
        baseline-on-migrate: true


    security:
        jwt:
            secret:
                key: 4f7d18bbb33b1f4d5af4ad61eea96f89c6102ad1e66aeb38d40f1cb7f9238afd
            expiration-time: 86400000
#        host-front: http://localhost:3000
