spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/db_shelfie
        username: shelfie
        password: password

    # JPA settings
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database: postgresql

    flyway:
        baseline-on-migrate: true

    security:
        jwt:
            secret:
                key: 4f7d18bbb33b1f4d5af4ad61eea96f89c6102ad1e66aeb38d40f1cb7f9238afd
            expiration-time: 86400000

springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui

