name: deploy-rest-api-shelfie

on:
  push:
    branches:
      - gms--back-api
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Set up JDK 17
#        uses: actions/setup-java@v2
#        with:
#          distribution: 'adopt'
#          java-version: '17'

#      - name: Build with Maven
#        run: mvn clean package -Dmaven.test.skip=true

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /root/Shelfie-back-end || git clone git@github.com:shelfiie/Shelfie-back-end.git
            cd /root/Shelfie-back-end
            git checkout gms--back-api
            git pull
            mvn package -Dmaven.test.skip=true
            PID=$(pgrep -f "shelfie-0.0.1-SNAPSHOT.jar")
            if [ -n "$PID" ]; then
              kill "$PID"
            fi
            nohup java -jar target/shelfie-0.0.1-SNAPSHOT.jar > log.txt 2>&1 &


